<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11" />
  </ItemGroup>

</Project>
